CREATE TABLE [dbo].[HWaveWoneItem]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	[Title] NVARCHAR(200) NULL,
	[LastModify] DATETIME2 NULL,
	[P] FLOAT NULL,
	[G] FLOAT NULL,
	[K] FLOAT NULL,
	[nu] FLOAT NULL,
	[Fimax] FLOAT NULL,
	[W] FLOAT NULL
)
