CREATE TABLE [dbo].[HWaveESourceItem]
(
	[HWaveESourceItemId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	[HWaveEItemId] UNIQUEIDENTIFIER NULL, 

	[X] FLOAT NULL,
	[Y] FLOAT NULL,
	[P] FLOAT NULL,
	[G] FLOAT NULL,
	[K] FLOAT NULL,
	[nu] FLOAT NULL,
	[E] FLOAT NULL,
	[Alfa1] FLOAT NULL,
	[Alfad] FLOAT NULL



	CONSTRAINT FK_HWaveESourceItemId_HWaveEItemId FOREIGN KEY (HWaveEItemId)
    REFERENCES HWaveEItem(HWaveEItemId)
)
